### ISSUE TITLE
Seeing lots of 503 and some 504 errors

### ISSUE THREAD

**Issue by jarenisenbeck** [soundcloud/api#354]
## Title: SoundCloud API is responding with 503 errors and occasional 504 errors
Issue found of: January 9 - January 11, 2024

### Endpoint(s):
* `GET /users/{id}/followers`
* `GET /users/{id}/followings`

### Scope(s):
* OAuth

### Steps to reproduce:

```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/{id}/followings?linked_partitioning=1&page_size=200'
```

```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/{id}/followers?linked_partitioning=1&page_size=200'
```

NOTE: sometimes the initial request succeeds but subsequent requests to the `next_href` in the response almost always result in a 503

### Expected behaviour:
A list of users as described at `https://developers.soundcloud.com/docs/api/explorer/open-api#/users/get_users__user_id__followings`.

and 

`https://developers.soundcloud.com/docs/api/explorer/open-api#/users/get_users__user_id__followers`

### Actual behaviour:
503 Server Error (not consistently)

error message when 503:
`upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 113`

some times 504 errors. When this happens, the error message is an empty string

**Comment by blackarcanis** [comment]
Hi!
We are also getting many 500 HTTP errors at this time. A temporary down of the API?

**Comment by mgoodfellow** [comment]
Hi,

We are also seeing this - it seems that around 15:00 on the 9th January, the response times and failure rates (5xx) responses on the API have been peaking:

![image](https://github.com/user-attachments/assets/076ced60-5ce0-46a9-948f-e4a47fc3b343)

Seems to be similar to https://github.com/soundcloud/api/issues/346 - but this time we are seeing 5xx errors (503 mainly) rather than the internal 404 error which was reported on this previous issue.

Cheers!

**Comment by dpreussler** [comment]
@jarenisenbeck @mgoodfellow thanks for reporting. 
We've found an issue that started last week indeed, should be fixed now

**Comment by jarenisenbeck** [comment]
@dpreussler I am continuing to see this issue even after you said that it should be fixed. Is it possible to re-open this issue?

**Comment by dpreussler** [comment]
@jarenisenbeck and you are still seeing these for the following endpoints or some other?

**Comment by jarenisenbeck** [comment]
@dpreussler Yes, I am still seeing `503` errors for these endpoints:

- `GET /users/{id}/followers`
- `GET /users/{id}/followings`

and also some 503s for
- `GET /users/{id}`

**Comment by mgoodfellow** [comment]
We are seeing the issues ongoing as well:

![image](https://github.com/user-attachments/assets/4f931ca9-1aa4-47dd-9d61-8b7798de4b10)

Pretty much all endpoints we used are affected (users, tracks, playlists, reposts, likes, comments etc). In addition we are seeing spikes in authentication endpoints (token grant/refresh)

We generally see a spike in response times, then a spike in 503s afterwards. It recovers for a bit, then spikes again.

Graph for the last 12 hours:

![image](https://github.com/user-attachments/assets/94fee206-6cc7-4f0e-98bd-8428aa9b3229)

In the last hour or so (since 16:30 UTC) it has degraded further, and this is causing our circuit breakers to fire as the failure rate is so high.

**Comment by dpreussler** [comment]
@mgoodfellow @jarenisenbeck thanks for your details. I can confirm we are having issues on various endpoints: tracks, playlists and profiles. Engineers are actively working on it and should be fixed by end of the week. Sorry for the inconveniences

**Comment by hubentom** [comment]
@dpreussler any update, we are still experiencing this

**Comment by dpreussler** [comment]
@hubentom the issue is still ongoing, sorry about that!

**Comment by dpreussler** [comment]
Update: the issue is ongoing and probably will only be solved by early next week.

**Comment by dpreussler** [comment]
Hi everyone, the elevated errors should be gone. 
Please let us know if you still seeing issues! 
Otherwise will close this ticket end of the week! Thanks for everyones' patience!

**Comment by Benjaminhu** [comment]
@dpreussler I restarted the synchronization (upload) and the track was uploaded successfully, thank you!

**Comment by jarenisenbeck** [comment]
Thank you @dpreussler. I can confirm that I am no longer seeing the 503 issue.

**Comment by hubentom** [comment]
thank you

**Comment by aterras** [comment]
Hi, I've been getting 503s again today with the same user endpoints (GET /users/{id}/followers & GET /users/{id}/followings, as well as GET /users/{id}/tracks, which hadn't been mentionned yet in this thread). 

Happened sparsely in the beginning of the afternoon, and is quite constant right now.
