### ISSUE TITLE
Playlist creation giving 500 - Internal Server Error

### ISSUE THREAD

**Issue by neil-amp** [soundcloud/api#36]
## Title: Playlist creation giving 500 - Internal Server Error
Issue found on: 22nd Feb 2021 

### Endpoint(s):
* POST https://api.soundcloud.com/v1/playlists

### Steps to reproduce:

Using PHP SDK:

$params = array(
'playlist[title]' => $title,
'playlist[description]' => $description,
'playlist[artwork_data]' => '@'.$path_to_image,
'playlist[sharing]' = 'private'
);
$sc_playlist = json_decode($sc_client->post('playlists', $params ));

### Expected behaviour:
Create a new playlist

### Actual behaviour:
500 Server Error (consistently)
{"code":500,"message":"","link":"https://github.com/soundcloud/api","status":"500 - Internal Server Error","errors":[],"error":null}

We did have this problem just with some uploads which seemed to be related to the image files (as fixed by reducing the size of them) but now seems to be failing for all uploads. Uploading individual tracks is fine, only playlist creation is failing. Tested from multiple servers and multiple different images / details.

**Comment by blackarcanis** [comment]
I can confirm we are getting the same problem when trying to upload an image to an existing playlist. 
The issue appears only a few days ago.

**Comment by alexweinstein** [comment]
Confirming that updating playlist artwork is broken as of a few days ago.

**Comment by rahul-sc** [comment]
Hello, all. Thanks for reporting. We're actively looking into this.

**Comment by docterd** [comment]
I cannot confirm this issue. Should it not be the endpoint `https://api.soundcloud.com/playlists` and not `https://api.soundcloud.com/v1/playlists` ?

**Comment by blackarcanis** [comment]
The issue seems fixed now, we don't have log error anymore and could upload the playlist cover again.

**Comment by neil-amp** [comment]
Sorry still not working for us - and to confirm my original issue report was for creating a new playlist, not updating the image on an existing one, thanks.

**Comment by rahul-sc** [comment]
This should have been fixed now. Can you please review and confirm?

**Comment by blackarcanis** [comment]
> This should have been fixed now. Can you please review and confirm?

Got an error 500 again today when trying to create a playlist. Since only a few hours I think. Could you check, please?

**Comment by rahul-sc** [comment]
> > This should have been fixed now. Can you please review and confirm?
> 
> Got an error 500 again today when trying to create a playlist. Since only a few hours I think. Could you check, please?

Can you share your request / response details, please?

**Comment by blackarcanis** [comment]
Method: POST 
URL: https://api.soundcloud.com/playlists 
Headers: Content-type: application/json, Authorization: OAuth xxxxx
BODY: {"playlist":{"title":"test","description":"testdesc","sharing":"private"}}

Is returning => 
`{"errors":[{"error_message":"500 - Internal Server Error"}]} `

**Comment by neil-amp** [comment]
Hey, 

It changes to giving a 404 error: The requested URL responded with HTTP code 404.

It seems to be an issue with the PHP SDK - https://github.com/mptre/php-soundcloud - I guess it's very outdated is there a newer version available?

I've fixed the issue by making the SDK call 

https://api.soundcloud.com/playlists 

rather than 

https://api.soundcloud.com/v1/playlists

Hopefully this might help someone else with similar problems.
