### ISSUE TITLE
SC Widget - Using URN format causes comments etc. to not load correctly

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#416]
Hi,

Following on from https://github.com/soundcloud/api/issues/397 - we swapped over to using URNs and noticed the widgets seem to fail to load comments etc:

Using URN format for the url:

![Image](https://github.com/user-attachments/assets/3722e4f9-2c28-4078-8e6a-e08fca567702)

As opposed to this, when the widget is loaded with the id.

Using ID format for the url:

![Image](https://github.com/user-attachments/assets/b47b67b4-54e4-4ae6-8314-e6ca9be66eb4)

Thanks!

**Comment by dpreussler** [comment]
@mgoodfellow  thanks for reporting. We'll prioritize this!

**Comment by dpreussler** [comment]
@mgoodfellow  should be fixed, thanks for reporting!

**Comment by mgoodfellow** [comment]
Hi @dpreussler, I'm still not seeing comments on some of the tracks?

**Comment by dpreussler** [comment]
@mgoodfellow  I just saw this. can you send some details?

**Comment by mgoodfellow** [comment]
Hi @dpreussler,

Sure:

<img width="1586" height="507" alt="Image" src="https://github.com/user-attachments/assets/44c2068c-af82-4bf7-af1b-a3219853318b" />

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Test URN Players</title>
  </head>
  <body style="margin:0">
<div style="margin: 20px">
SRC: https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false
</div>
<div style="margin: 20px">
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mike-goodfellow" title="Mike Goodfellow" target="_blank" style="color: #cccccc; text-decoration: none;">Mike Goodfellow</a> · <a href="https://soundcloud.com/mike-goodfellow/io-moon" title="Io" target="_blank" style="color: #cccccc; text-decoration: none;">Io</a></div>
</div>
<div style="margin: 20px">
SRC: https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud:tracks:829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false
</div>
<div style="margin: 20px">
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud:tracks:829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mike-goodfellow" title="Mike Goodfellow" target="_blank" style="color: #cccccc; text-decoration: none;">Mike Goodfellow</a> · <a href="https://soundcloud.com/mike-goodfellow/io-moon" title="Io" target="_blank" style="color: #cccccc; text-decoration: none;">Io</a></div>
</div>
  </body>
</html>
```

**Comment by mgoodfellow** [comment]
Same thing if we use the %3A encoding in the URL (like is used for the https%3A//...

<img width="1583" height="768" alt="Image" src="https://github.com/user-attachments/assets/5fe29f54-0391-49ea-9902-0f955f19461d" />

Snip

```
<div style="margin: 20px">
SRC: https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud%3Atracks%3A829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false
</div>
<div style="margin: 20px">
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud%3Atracks%3A829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mike-goodfellow" title="Mike Goodfellow" target="_blank" style="color: #cccccc; text-decoration: none;">Mike Goodfellow</a> · <a href="https://soundcloud.com/mike-goodfellow/io-moon" title="Io" target="_blank" style="color: #cccccc; text-decoration: none;">Io</a></div>
</div>
```

**Comment by mgoodfellow** [comment]
Hi @dpreussler 

This issue is still ongoing - in addition, the visual player is very broken:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Test URN Players</title>
  </head>
  <body style="margin:0">
<div style="margin: 20px">
SRC: https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false<br/>
DETAILS: Old ID format, shows comments
</div>
<div style="margin: 20px">
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mike-goodfellow" title="Mike Goodfellow" target="_blank" style="color: #cccccc; text-decoration: none;">Mike Goodfellow</a> · <a href="https://soundcloud.com/mike-goodfellow/io-moon" title="Io" target="_blank" style="color: #cccccc; text-decoration: none;">Io</a></div>
</div>
<div style="margin: 20px">
SRC: https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud:tracks:829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false<br/>
DETAILS: New URN format, doesn't show comments
</div>
<div style="margin: 20px">
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud:tracks:829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mike-goodfellow" title="Mike Goodfellow" target="_blank" style="color: #cccccc; text-decoration: none;">Mike Goodfellow</a> · <a href="https://soundcloud.com/mike-goodfellow/io-moon" title="Io" target="_blank" style="color: #cccccc; text-decoration: none;">Io</a></div>
</div>
<div style="margin: 20px">
SRC: https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud%3Atracks%3A829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false<br/>
DETAILS: New URN format (URL encoded), doesn't show comments
</div>
<div style="margin: 20px">
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud%3Atracks%3A829142212&color=%23ff5500&auto_play=false&hide_related=true&show_comments=true&show_user=true&show_reposts=true&show_teaser=false"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mike-goodfellow" title="Mike Goodfellow" target="_blank" style="color: #cccccc; text-decoration: none;">Mike Goodfellow</a> · <a href="https://soundcloud.com/mike-goodfellow/io-moon" title="Io" target="_blank" style="color: #cccccc; text-decoration: none;">Io</a></div>
</div>
<div style="margin: 20px">
SRC: https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud%253Atracks%253A829142212&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true<br/>
DETAILS: New URN format visual player, direct grab from SC share modal, shows comments
</div>
<div style="margin: 20px">
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/soundcloud%253Atracks%253A829142212&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/mike-goodfellow" title="Mike Goodfellow" target="_blank" style="color: #cccccc; text-decoration: none;">Mike Goodfellow</a> · <a href="https://soundcloud.com/mike-goodfellow/io-moon" title="Io" target="_blank" style="color: #cccccc; text-decoration: none;">Io</a></div>
</div>

  </body>
</html>
```

<img width="2739" height="1038" alt="Image" src="https://github.com/user-attachments/assets/a26578c9-1433-44fb-a8b9-fb426ee9b9a6" />

So, although the visual player shows the comments that are missing from the non-visual player, it behaves very strangely when you click on it.

If you try to skip around on the waveform, the track pauses, and shows it as if it has finished. If you then play it again, it shows its not playing anymore (play icon, not pause icon), but it is actively playing.

## It's hard to describe, but, the same behavioural issues exist in the share dialog itself on SoundCloud:

<img width="647" height="1094" alt="Image" src="https://github.com/user-attachments/assets/fd15bc38-66a3-4886-9f2d-379f82cc979a" />

## Click play, try to skip on waveform:

<img width="568" height="359" alt="Image" src="https://github.com/user-attachments/assets/ad8bff77-4fb1-4c78-b598-8220b8663c9a" />

## It's still playing, now click play, and it starts again (from the beginning of the track), but the waveform is frozen:

<img width="581" height="368" alt="Image" src="https://github.com/user-attachments/assets/462e3fea-4688-4c0e-a65e-a04f863d37b7" />

## Finally, in addition, the comments aren't rendered here in this view:

<img width="601" height="574" alt="Image" src="https://github.com/user-attachments/assets/10a8ecc3-5341-40d7-bd86-33288b0d19bf" />

Could this be resolved please as the visual player is rendered unusable due to these behavioural defects.

**Comment by dpreussler** [comment]
@mgoodfellow we'll try to have a look. 🙏

**Comment by dpreussler** [comment]
@mgoodfellow  so looking at your examples, it seems there is some weird double encoding happen (when using from the sc embed) but actually then it works 🤔  
Will keep you posted but this helps for sure

**Comment by mgoodfellow** [comment]
@dpreussler Good spot, however from my tests, the same issues are present regardless of encoding. It is almost like the visual player gets stuck in a reset loop (you can see the waveform reset on the initial play). Very strange. The other format (non-visual player) is more stable in that regard, but then we still have the missing comments on the waveform issue.

Fingers crossed you find the issues, thanks!

**Comment by mgoodfellow** [comment]
Hi @dpreussler 

Happy to report both issues have been fixed - comments appearing on the grey style player, and no more glitching issues with the waveform on the new player:

<img width="2746" height="1078" alt="Image" src="https://github.com/user-attachments/assets/7ba9d48f-35d2-49c4-add2-0dbb96d9d679" />

Many thanks for your help! 👍
