### ISSUE TITLE
GET /tracks "created_at" ignored

### ISSUE THREAD

**Issue by tkrosenblatt** [soundcloud/api#495]
Could be a coincidence but ever since [#489](https://github.com/soundcloud/api/issues/489) was resolved, the search /tracks endpoint has ignored the "created_at" param and returned the same list of tracks for any calls to this endpoint.

Possibly related: the created_at timestamps returned are yyyy/mm/dd hh:mm:ss +0000 not yyyy-mm-dd hh:mm:ss as expected. Attempting to mimic this format in the request param results in a Bad Request error, with or without the UTC offset.

Simplified requests examples (bug holds true for all access, linked_partitioning, etc values):
https://api.soundcloud.com/tracks?created_at%5Bfrom%5D=2025-12-21%2000%3A00%3A00&created_at%5Bto%5D=2025-12-22%2000%3A00%3A00
https://api.soundcloud.com/tracks?created_at%5Bfrom%5D=2025-12-15%2000%3A00%3A00&created_at%5Bto%5D=2025-12-16%2000%3A00%3A00
both return the same 49 tracks with the following created_at values outside of param values:

```
2025/09/18 16:07:31 +0000
2025/10/07 03:48:16 +0000
2025/10/23 16:38:27 +0000
2025/12/12 09:40:38 +0000
2025/12/04 05:59:37 +0000
2025/12/22 12:30:27 +0000
2025/12/22 12:30:31 +0000
2025/12/22 12:30:09 +0000
2025/12/22 12:29:50 +0000
2025/12/21 04:59:19 +0000
2025/10/14 07:39:23 +0000
2025/12/21 21:43:49 +0000
2025/12/19 10:13:46 +0000
2025/12/21 11:36:55 +0000
2025/12/22 12:30:01 +0000
2025/12/22 12:29:59 +0000
2025/12/22 12:30:21 +0000
2025/12/22 12:29:48 +0000
2025/12/22 12:29:49 +0000
2025/12/22 12:30:22 +0000
2025/12/22 12:30:39 +0000
2025/12/22 12:30:01 +0000
2025/12/22 12:30:17 +0000
2025/12/22 12:30:12 +0000
2025/12/22 12:29:59 +0000
2025/12/22 12:29:51 +0000
2025/12/22 11:16:59 +0000
2025/12/22 12:30:00 +0000
2025/12/22 12:30:29 +0000
2025/12/22 12:30:41 +0000
2025/12/22 12:30:30 +0000
2025/12/22 12:30:30 +0000
2025/12/22 12:30:30 +0000
2025/12/22 12:30:09 +0000
2025/12/22 12:30:23 +0000
2025/12/20 18:11:50 +0000
2025/12/22 12:29:49 +0000
2025/12/22 12:30:17 +0000
2025/12/22 12:30:06 +0000
2025/12/10 14:04:23 +0000
2025/12/22 12:30:02 +0000
2025/12/22 12:30:32 +0000
2025/12/22 12:29:52 +0000
2025/12/16 06:36:13 +0000
2025/12/22 12:30:00 +0000
2025/12/22 12:29:49 +0000
2025/12/22 12:30:37 +0000
2025/12/22 12:30:35 +0000
2025/12/21 15:29:37 +0000
```

**Comment by youssefhassan** [comment]
Hey @tkrosenblatt, it shouldn't be related to the 403 incident. Is it still happening that date range is not taken into account?

**Comment by tkrosenblatt** [comment]
Agree it shouldn't be, just flagging the coincidence. Yes, date range is still being ignored.

**Comment by tkrosenblatt** [comment]
@youssefhassan Any timeline of resolution / confirmation of repeatability / etc?

**Comment by tkrosenblatt** [comment]
Update: Instead of returning results ignoring the created_at param, now the API is returning an empty response [] status code 200 with **any** correctly formatted created_at values including those included as the example in the API spec:
https://api.soundcloud.com/tracks?created_at%5Bfrom%5D=2020-12-24%2000%3A00%3A00&created_at%5Bto%5D=2020-12-26%2000%3A00%3A00

Attempting to vary the datetime format to anything other than yyyy-mm-dd hh:mm:ss results in a Bad Request status code 400 still.

@youssefhassan @dpreussler any ideas or updates?

**Comment by tkrosenblatt** [comment]
Will keep leaving updated ideas from diagnostic info here I guess... the results are not always empty but they are seemingly always stuck with ~80% of the results returning falling into the correct window from a previous call and then results are frozen as such in following calls. I haven't worked how long they are frozen for but seems to be >24 hours. Appears to be a caching issue then. Please confirm.

**Comment by tkrosenblatt** [comment]
@youssefhassan @dpreussler please confirm?

**Comment by dpreussler** [comment]
@tkrosenblatt looking into it. Might have found something.. I'll come back to you early next week 🙏

**Comment by dpreussler** [comment]
we found sth, a fix has been merged and is rolling out. Can you check later today? @tkrosenblatt

**Comment by tkrosenblatt** [comment]
@dpreussler Still the same bug. Are you seeing different results when you test?

https://api.soundcloud.com/tracks?linked_partitioning=True&created_at%5Bfrom%5D=2026-02-16%2009:14:00&created_at%5Bto%5D=2026-02-17%2009:14:00
`{'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '119678', 'Connection': 'keep-alive', 'vary': 'Origin', 'x-robots-tag': 'noindex', 'cache-control': 'public, max-age=60, must-revalidate', 'referrer-policy': 'no-referrer', 'x-frame-options': 'DENY', 'x-content-type-options': 'nosniff', 'strict-transport-security': 'max-age=63072000; includeSubdomains; preload', 'server': 'am/2', 'date': 'Tue, 17 Feb 2026 14:15:01 GMT', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 00266a01055b9f1e1ad959f077c1d96a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'JFK50-P6', 'X-Amz-Cf-Id': 'CZqtsVY8oh2NEWNKd6p9X2ZJyp_KN-izzzWtQ69w6tSmLiXqMnF3xw=='}`

https://api.soundcloud.com/tracks?linked_partitioning=True&created_at%5Bfrom%5D=2026-02-15%2009:14:00&created_at%5Bto%5D=2026-02-16%2009:14:00
`{'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '119678', 'Connection': 'keep-alive', 'vary': 'Origin', 'x-robots-tag': 'noindex', 'cache-control': 'public, max-age=60, must-revalidate', 'referrer-policy': 'no-referrer', 'x-frame-options': 'DENY', 'x-content-type-options': 'nosniff', 'strict-transport-security': 'max-age=63072000; includeSubdomains; preload', 'server': 'am/2', 'date': 'Tue, 17 Feb 2026 14:16:02 GMT', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 00266a01055b9f1e1ad959f077c1d96a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'JFK50-P6', 'X-Amz-Cf-Id': 'y3Ejl7OivrU7EY-FQ18G8FBaeSrX9wBMCmqkIaJv-PZAFu0PKD4SJw=='}`

**Comment by tkrosenblatt** [comment]
PS something in your merge now has all calls to /resolve regardless of auth or origin returning Rate Limit Exceeded.

**Comment by dpreussler** [comment]
@tkrosenblatt  thats not related but another user was reaching out as of 429
Can you open a new issue for that for visibitliy with details you have?

**Comment by dpreussler** [comment]
@tkrosenblatt  are you still seeing this 429 error? We just reverted some configuration change

**Comment by tkrosenblatt** [comment]
Confirming 429 /resolve is fixed now. Didn't mean to confuse from the actual ticketed /tracks query cache bug that's the priority, just chiming in while I'm here...

**Comment by dpreussler** [comment]
nah thanks for raising. The moment you raised it, i could make the connection to another report! 

Now looking back at your's here. Def something weird caching wise, we're still investigating

**Comment by tkrosenblatt** [comment]
/oauth/token now 429 possibly all others but can't get past the door

**Comment by dpreussler** [comment]
@tkrosenblatt should be fine again! Sorry about this done. We'll work tomorrow on stabilizing this one

**Comment by dpreussler** [comment]
@tkrosenblatt  btw the reason you have these auth issues (and not many others are running into this) is that you're using the deprecated endpoints! Please migrate to Oauth 2.1! 
From April 1st on this endpoint will be shut down: https://github.com/soundcloud/api/discussions/515

**Comment by tkrosenblatt** [comment]
[/oauth/token](https://secure.soundcloud.com/oauth/token) is the 2.1 endpoint... I migrated from https://api.soundcloud.com/oauth2/token Jan 16 2025

**Comment by dpreussler** [comment]
Are you saying you got 429 from secure.soundcloud.com? That's interesting 

![](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExY3p1cmp5ZWs5cjdkenkxb3RxMnp1NnExMmJhNGo3MXdnOTk3cDA1OSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/n8SkNR77udWlG/giphy.gif)

**Comment by tkrosenblatt** [comment]
Yes 3.5 hours ago but 200 just now

**Comment by dpreussler** [comment]
Ok if it reappear please open new thread to keep this one about created_at
I can reproduce this one (sometimes), looking into it

**Comment by tkrosenblatt** [comment]
@dpreussler Just checking back in re created_at cache key

**Comment by dpreussler** [comment]
@tkrosenblatt sorry I was off for a week. Will come back you!

**Comment by tkrosenblatt** [comment]
@dpreussler Just checking back in

**Comment by dpreussler** [comment]
@tkrosenblatt  I still have your issue on my list to check. sorry for the delay. You are not forgotten 🙏

**Comment by tkrosenblatt** [comment]
@dpreussler feeling forgotten!

**Comment by dpreussler** [comment]
@tkrosenblatt not forgotten
I think I found it, hope to get it rolled out these days

**Comment by dpreussler** [comment]
should be live within the hour! Sorry for the long wait time. We're bit understaffed rn

**Comment by tkrosenblatt** [comment]
Thank you!
